### ISSUE TITLE
<prismic-link> doesn't use linkResolver unless passed as prop

### ISSUE THREAD

**Issue by evvvritt** [prismicio/prismic-vue#40] opened 2020-12-09 18:02 UTC
Hi, I've never had a problem using `<prismic-link>` but currently it doesn't use the linkResolver unless it's passed into the component as a prop?

[sandbox example](https://codesandbox.io/s/prismic-link-doesnt-use-linkresolver-6emik?file=/src/link-resolver.js)

**Comment by lihbr** [comment] 2021-01-18 13:56
Hey @evvvritt, I'm really sorry you didn't get proper support back then. Usually, our [community forum](https://community.prismic.io/c/kits-and-dev-languages/vue-js/16) can get you support quickly. I hope you figured out a workaround since then!

Thanks for the issue also as it made us realize that indeed `prismic-vue` is not supplying the link resolver to `prismic-link` automatically which is a bummer, I'll look forward to fix that!

**Comment by evvvritt** [comment] 2021-01-18 14:30
Thanks @lihbr ! I’ve also noticed prismic-rich-text having issues inheriting linkResolver (or htmlSerializer) from the config. :/
I’m just using my own components for now but best of luck and thanks.

**Comment by lihbr** [comment] 2021-01-18 14:31
Yeah, apparently that's something thta has been done for Nuxt but not for Vue itself so far, thanks!

**Comment by lihbr** [comment] 2021-03-12 17:05
Hey, I went through that again, turns out it was a valid bug! Got fixed in 2.0.11, thanks for reporting! I wasn't able to detect anything wrong with the rich text component, let me know if you have a reproduction, I'll reopen!

**Closed by lihbr** 2021-03-12 17:05 UTC
Labels: bug
